FROM codercom/enterprise-base:centos

# Run everything as root
USER root

# Install OpenSSL library
RUN yum install -y openssl-devel

# Install Ruby from source
COPY ./install-ruby.sh /tmp
RUN chmod +x /tmp/install-ruby.sh && /tmp/install-ruby.sh

# Install bundler gem
RUN gem install bundler

# Set back to coder user
USER coder
