FROM codercom/enterprise-base:ubuntu

# Run everything as root
USER root

# Install Ruby
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y ruby-full

# Install bundler gem
RUN gem install bundler

# Set back to coder user
USER coder
