FROM codercom/enterprise-base:ubuntu

# Run everything as root
USER 0

# Install OpenSSL library
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y libssl-dev

# Install Ruby from source
COPY ./install-ruby.sh /tmp
RUN chmod +x /tmp/install-ruby.sh && /tmp/install-ruby.sh

# Set back to coder user
USER 1000
