FROM codercom/enterprise-base:ubuntu

# Run everything as root
USER root

# Install JDK (OpenJDK 14)
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y openjdk-14-jdk

# Set back to coder user
USER coder
