FROM bravo68web/cdr-enterprise-base:ubuntu

# Run everything as root
USER root

# Install jupyter
RUN pip3 install jupyter-core==4.11.1 && \
    pip3 install jupyterlab==3.4.3 && \
    pip3 install notebook==6.4.12

# Set back to coder user
USER coder
