FROM bravo68web/cdr-enterprise-base:centos

# Run everything as root
USER root

# Install required dependencies
RUN dnf install --assumeyes \
   platform-python-devel

# Install jupyter
RUN python3 -m pip install --upgrade pip && \
    pip3 install --upgrade setuptools && \
    pip3 install jupyter-core==4.7.1 && \
    pip3 install jupyterlab && \
    pip3 install notebook

# Set back to coder user
USER coder
