FROM codercom/enterprise-java:ubuntu

# Run everything as root
USER root

# Packages required for multi-editor support
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y \
    libxtst6 \
    libxrender1 \
    libfontconfig1 \
    libxi6 \
    libgtk-3-0

# Install Android Studio
RUN add-apt-repository ppa:maarten-fonville/android-studio && \
    apt update && \
    apt install -y android-studio && \
    ln -s /opt/android-studio/bin/studio.sh /usr/local/bin/studio

USER coder