FROM ubuntu:20.04

RUN apt-get update && apt-get install -y \
    sudo \
    python3 \
    python3-pip

# Install jupyter
RUN pip3 install jupyterlab

# Add a user `coder` so that you're not developing as the `root` user
RUN adduser --gecos '' --disabled-password coder && \
  echo "coder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/nopasswd
USER coder
