FROM ubuntu:22.04

USER root
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        bash \
        ca-certificates \
        curl \
        git

RUN useradd coder \
        --create-home \
        --shell=/bin/bash \
        --uid=1000 \
        --user-group

RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

USER coder