FROM codercom/enterprise-multieditor:centos

# Run everything as root
USER root

# Install DataSpell.
RUN mkdir -p /opt/dataspell
RUN curl -L "https://download-cdn.jetbrains.com/python/dataspell-2021.3.3.tar.gz" | tar -C /opt/dataspell --strip-components 1 -xzvf -

# Add a binary to the PATH that points to the pycharm startup script.
RUN ln -s /opt/dataspell/bin/dataspell.sh /usr/bin/dataspell

# Set back to coder user
USER coder