FROM codercom/enterprise-base:centos

# Run everything as root
USER root

# Install whichever Node version is LTS
RUN curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
RUN yum install -y nodejs

# Install Yarn
RUN curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | tee /etc/yum.repos.d/yarn.repo
RUN yum install -y yarn

# Set back to coder user
USER coder
