FROM codercom/enterprise-multieditor:ubuntu

# Run everything as root
USER root

# Install intellij & java.
RUN mkdir -p /opt/idea
RUN curl -L "https://download.jetbrains.com/product?code=IIC&latest&distribution=linux" | tar -C /opt/idea --strip-components 1 -xzvf -
RUN sudo apt install default-jre -y

# Add a binary to the PATH that points to the intellij startup script.
RUN ln -s /opt/idea/bin/idea.sh /usr/bin/intellij-idea-community

# Set back to coder user
USER coder
