FROM codercom/enterprise-base:ubuntu

# Run everything as root
USER 0

# Packages required for multi-editor support
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y \
    libxtst6 \
    libxrender1 \
    libfontconfig1 \
    libxi6 \
    libgtk-3-0

# Set back to coder user
USER 1000
